version: '3'
services:
  web:
    container_name: vws-webserver
    image: nginx:latest
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - db
    networks:
      - vws-network
  php-fpm:
    container_name: vws-php
    image: php:5.6-fpm
    volumes:
      - .:/var/www/html
    networks:
      - vws-network
  db:
    container_name: vws-db
    # image: mysql:5.7 #for amd -> arm not support
    image: mysql:8 #for amd
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - vws-network
networks:
  vws-network:
    driver: bridge
volumes:
  dbdata: